minetest.register_privilege("chapters:chapter_1_started",{description = "You have started chapter 1"})
minetest.register_privilege("chapters:chapter_1_complete",{description = "You have completed chapter 1"})
minetest.register_privilege("chapters:chapter_2_started",{description = "You have started chapter 2"})
minetest.register_privilege("chapters:chapter_2_complete",{description = "You have completed chapter 2"})
minetest.register_privilege("chapters:chapter_3_started",{description = "You have started chapter 3"})
minetest.register_privilege("chapters:chapter_3_complete",{description = "You have completed chapter 3"})
minetest.register_privilege("chapters:chapter_4_started",{description = "You have started chapter 4"})
minetest.register_privilege("chapters:chapter_4_complete",{description = "You have completed chapter 4"})